#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <flippermon_icons.h>

int32_t flippermon_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm myapp!");

    return 0;
}
